# Generated by Django 4.0.3 on 2022-03-22 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published'], 'verbose_name_plural': 'Articles'},
        ),
        migrations.AddField(
            model_name='article',
            name='series',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.articleseries', verbose_name='Series'),
        ),
    ]
