# Generated by Django 4.0.3 on 2022-04-04 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_article_slug_alter_article_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='slug',
            new_name='article_slug',
        ),
    ]
